@extends('main.layouts.master')
@section('title', $pageTitle)
@section('content')


<section id="section" class="py-5">
     <div class="container"> <div class="row"> <div class="col-12 mb-4"> <h5 class="page-name">{{$pageTitle}}</h5> </div> @include('main.user.aside') <div class="col-lg-9"> <div class="row"> @if (getAuth('user', 'email_verified_at')==null) <div class="col-12"> <div class="box-white py-5 text-center"> <h5 class=" text-center mb-3">قبل ارسال الطلبات يجب تاكيد بريدك الالكتروني</h5> <form class="d-inline-block" action="{{userUrl('email-verification')}}" method="post"> @csrf <button type="submit" class="btn-main">تأكيد حسابي</button> </form> </div></div>@else <div class="col-12 mb-3"> <h5 class=" float-right">بحث جديد</h5> <a href="{{userUrl('researches/all')}}" class="btn-main float-left">ابحاثي</a> </div><div class="col-lg-12"> <div class="box-white p-3"> <div class="result"></div>@if (session()->has('successMsg')) <div class=" alert alert-success text-center">{{session()->get('successMsg')}}</div>@endif <form class="form" id="form-create-users-researches" action="{{userUrl('researches/store')}}" method="POST" enctype="multipart/form-data"> @csrf <div class="form-group"> <label class="required">عنوان البحث</label> <input type="text" name="title" class="form-control"> </div><div class="form-group"> <label class="required">الكلمات المفتاحية</label> <textarea name="keywords" class="form-control" cols="30" rows="3"></textarea> </div><div class="form-group"> <label class="required">ملخص البحث</label> <textarea name="abstract" class="form-control" cols="30" rows="10"></textarea> </div><div class="form-group"> <label class="required">نوع البحث</label> <select name="type" class="form-control"> <option selected disabled>اختر</option> <option value="1">مقيد الوصول</option> <option value="0">مفتوح المصدر</option> </select> </div><div class="form-group"> <label class=" required">اختر مجلة للنشر</label> <select name="journal" class="form-control"> <option selected disabled>اختر</option> @foreach ($journals as $jour) <option value="{{$jour->id}}">{{$jour->name}}</option> @endforeach </select> </div><div class="form-group mb-4"> <label class="required">ملف البحث</label> <input type="file" name="file" accept=".doc,.docx" class="form-control"> <small class="d-block text-left text-muted">انواع الملفات (doc/docx) فقط هي التي يتم قبولها</small> </div><div class="form-group mb-2"> <button type="submit" class="btn-main btn-block">ارسال</button> </div></form> </div></div>@endif </div></div></div></div>
     
</section>
     
@endsection